name: Hello with docker
on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        id: hello-action
        uses: ./.github/actions/hello-world-docker-action
        with:
          who-to-greet: 'madinsoft'

      - name: Show output
        run: echo "the time ${{ steps.hello-action.outputs.time }}
    
  
    
