name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'test'
          echo 'autre ligne'
      - uses: actions/checkout@v3.3.0
      - name: Use action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'madinsoft'
