name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. TÉLÉCHARGEMENT DU CODE (DOIT ÊTRE LA PREMIÈRE ÉTAPE !)
      - uses: actions/checkout@v3.3.0

      # 2. Utilisation de l'action locale (maintenant le dossier existe)
      - name: Use action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'madinsoft'

      # 3. Autres commandes/tests (optionnel)
      - run: |
          echo 'test'
          echo 'autre ligne'
      - run: tree
